import "server-only";

import { escapeHtml, inline, paragraphs } from "@/lib/studio/inline";
import { readWrapperFile, WRAPPER_FILES } from "@/lib/studio/template";
import type { CourseDraft, TopicDraft } from "@/types/studio";

/* Generates the LACE course package from a draft, faithful to the structures
   in brightspace-courses/Course-Template. Only course-config.js and the topic
   pages are generated — Home.html and complete.html render themselves from
   the config at runtime and ship verbatim. Text helpers (escape + markdown-
   lite) live in lib/studio/inline.ts, shared with the live preview. */

export { escapeHtml, inline };

function jsString(text: string): string {
  return JSON.stringify(text);
}

/* ── course-config.js ────────────────────────────────────────────────────── */

export function generateConfigJs(draft: CourseDraft): string {
  const modules = draft.modules
    .map((mod) => {
      const topics = mod.topics
        .map(
          (t) => `        {
          slug: ${jsString(t.slug)},
          title: ${jsString(t.title)},
          file: ${jsString(`${t.slug}.html`)},
          // Paste the Brightspace content-topic URL here after upload, then
          // switch deployMode to "lms" and re-upload this file.
          url: "#",
          kind: ${jsString(t.kind)},
          minutes: ${t.minutes || 0},${t.updated ? `\n          updated: ${jsString(t.updated)},` : ""}
          description: ${jsString(t.description)},
        }`,
        )
        .join(",\n");
      return `    {
      id: ${jsString(mod.id)},
      title: ${jsString(mod.title)},
      accent: ${jsString(draft.topic)},
      description: ${jsString(mod.description)},
      topics: [
${topics}
      ],
    }`;
    })
    .join(",\n");

  return `/**
 * Course Configuration — single source of truth for the LACE wrapper.
 * Generated by Brightspace Manager Course Studio. Safe to edit by hand.
 *
 * WORKFLOW: test locally with deployMode "local" → upload the package to
 * Brightspace Manage Files → create a Content topic per page → paste each
 * topic URL into \`url\` → switch deployMode to "lms" → re-upload this file.
 */

window.COURSE_CONFIG = {
  deployMode: "local",
  chromeMode: ${jsString(draft.chromeMode)},
  courseId: ${jsString(draft.courseId)},

  courseTitle: ${jsString(draft.courseTitle)},
  courseSubtitle: ${jsString(draft.courseSubtitle)},
  // Rendered via innerHTML on the outline page — markdown becomes HTML here.
  courseBlurb: ${jsString(inline(draft.courseBlurb || draft.courseSubtitle))},

  hubLabel: "Hub",
  courseArea: ${jsString(draft.courseArea)},

  topic: ${jsString(draft.topic)},

  homeLinkText: "Exit to Hub",
  homeLinkUrl: ${jsString(draft.homeLinkUrl)},

  // Local mode targets; replace with Brightspace URLs at deploy time.
  courseHomeUrl: "Home.html",
  completeUrl: "complete.html",

  modules: [
${modules}
  ],
};
`;
}

/* ── topic pages ─────────────────────────────────────────────────────────── */

function tryItSection(topic: TopicDraft): string {
  const options = topic.tryIt.options
    .filter((o) => o.text.trim())
    .map(
      (o) => `          <button class="tryit-option" type="button" data-correct="${o.correct}">
            <span class="tryit-radio"></span>
            <span>${inline(o.text)}</span>
          </button>`,
    )
    .join("\n");

  return `    <!-- ── § 4 · Try it ─────────────────────────────────────────────────── -->
    <section class="section">
      <div class="section-rule">
        <span class="sr-num">§ 4</span>
        <span class="sr-line"></span>
        <span class="sr-label">Try it</span>
      </div>
      <p class="prose" style="font-style:italic;color:var(--muted);">
        One question. You'll see the answer once you choose.
      </p>
      <div class="tryit-box">
        <div class="eyebrow">Scenario</div>
        <p class="tryit-q">${inline(topic.tryIt.question)}</p>
        <div class="tryit-options">
${options}
        </div>
        <div class="answer-banner hidden">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
               stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="m5 12 4 4L19 6"/>
          </svg>
          <span><strong>The answer:</strong> ${inline(topic.tryIt.answer)}</span>
        </div>
      </div>
    </section>`;
}

function whatChangedSection(topic: TopicDraft): string {
  const wc = topic.whatChanged;
  if (!wc || !wc.heading.trim()) return "";
  return `    <!-- ── § 3 · What changed ───────────────────────────────────────────── -->
    <section class="section">
      <div class="section-rule rust">
        <span class="sr-num">§ 3</span>
        <span class="sr-line"></span>
        <span class="sr-label">What changed</span>
      </div>
      <div class="changed-box">
        <div class="cb-meta">
          <span class="pill pill-rust">${inline(wc.pill || "Law changed")}</span>
          <span class="eyebrow eyebrow-muted">${inline(wc.meta)}</span>
        </div>
        <h3>${inline(wc.heading)}</h3>
        <p>${inline(wc.body).replace(/\r?\n/g, " ")}</p>
      </div>
    </section>
`;
}

/* Media figures — markup is self-contained (inline styles on wrapper CSS
   variables with fallbacks) because course-style.css has no figure rules
   yet. When the official look lands, move this styling into the wrapper
   and slim the inline styles here. */
function mediaFigures(topic: TopicDraft, placement: "scenario" | "rule"): string {
  const figures = (topic.media ?? []).filter((m) => m.placement === placement && m.filename.trim());
  if (figures.length === 0) return "";
  return (
    figures
      .map(
        (m) => `      <figure class="media-figure" style="margin:1.25rem 0;">
        <img src="images/${escapeHtml(m.filename.trim())}" alt="${escapeHtml(m.alt)}"
             style="display:block;max-width:100%;border:1px solid var(--line, #e4e7ed);border-radius:10px;" />${
               m.caption.trim()
                 ? `\n        <figcaption style="margin-top:0.5rem;font-size:0.8rem;color:var(--muted, #565c69);">${inline(m.caption)}</figcaption>`
                 : ""
             }
      </figure>`,
      )
      .join("\n") + "\n"
  );
}

function ruleBox(topic: TopicDraft): string {
  const items = topic.ruleBoxItems.filter((i) => i.trim());
  if (items.length === 0) return "";
  return `      <div class="rule-box">
        <div class="eyebrow">${inline(topic.ruleBoxLabel || "The rule")}</div>
        <ol>
${items.map((i) => `          <li>${inline(i)}</li>`).join("\n")}
        </ol>
      </div>
`;
}

function nextUpSection(draft: CourseDraft, flatIndex: number, flat: TopicDraft[]): string {
  const next = flat[flatIndex + 1];
  if (next) {
    return `    <!-- ── Next up ──────────────────────────────────────────────────────── -->
    <section class="next-up">
      <p class="eyebrow eyebrow-muted">Up next · Topic ${flatIndex + 2} of ${flat.length}</p>
      <a class="next-up-card" href="#" data-lace="next-link">
        <span class="nu-body">
          <span class="cb-meta" style="display:flex;gap:8px;">
            <span class="pill pill-rust">${inline(next.kind)} · ${next.minutes} min</span>${
              next.updated ? `\n            <span class="pill pill-rust">● ${inline(next.updated)}</span>` : ""
            }
          </span>
          <span class="nu-title">${inline(next.title)}</span>
          <span class="nu-sub">${inline(next.description)}</span>
        </span>
        <span class="next-up-go">
          Continue
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
               stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M5 12h14"/><path d="m13 6 6 6-6 6"/>
          </svg>
        </span>
      </a>
    </section>`;
  }
  return `    <!-- ── Next up: finish ──────────────────────────────────────────────── -->
    <section class="next-up">
      <p class="eyebrow eyebrow-muted">That was the last topic</p>
      <a class="next-up-card" href="#" data-lace="next-link">
        <span class="nu-body">
          <span class="nu-title">Finish the course</span>
          <span class="nu-sub">See your completion summary.</span>
        </span>
        <span class="next-up-go">
          Finish
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
               stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M5 12h14"/><path d="m13 6 6 6-6 6"/>
          </svg>
        </span>
      </a>
    </section>`;
}

export function generateTopicHtml(draft: CourseDraft, slug: string): string {
  const flat = draft.modules.flatMap((m) => m.topics);
  const flatIndex = flat.findIndex((t) => t.slug === slug);
  if (flatIndex === -1) throw new Error(`No topic with slug "${slug}".`);
  const topic = flat[flatIndex];

  /* Section numbering shifts when §3 is omitted — match the template's
     committed structure: scenario=1, rule=2, [changed=3,] try-it, remember. */
  const hasChanged = Boolean(topic.whatChanged && topic.whatChanged.heading.trim());
  const tryItNum = hasChanged ? 4 : 3;
  const rememberNum = hasChanged ? 5 : 4;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(topic.title)}</title>

  <!-- Generated by Brightspace Manager Course Studio. -->
  <meta name="course-slug" content="${escapeHtml(topic.slug)}">

  <link rel="stylesheet" href="course-style.css">
  <script src="course-config.js"></script>
  <!-- Apply the course's topic accent before paint, so there is no colour flash. -->
  <script>document.documentElement.dataset.topic = (window.COURSE_CONFIG || {}).topic || "foundations";</script>
  <script src="course-nav.js" defer></script>
</head>
<body>

<div class="page">
  <!-- Chrome bar (breadcrumb + prev/next) injected by course-nav.js -->
  <div id="lace-nav-container"></div>

  <main class="page-body topic-body">

    <!-- ── Topic header ─────────────────────────────────────────────────── -->
    <p class="eyebrow">Topic ${flatIndex + 1} of ${flat.length} · ${escapeHtml(topic.kind)} · ${topic.minutes} min</p>
    <h1 class="display topic-title">${inline(topic.title)}</h1>
    <p class="topic-standfirst">${inline(topic.standfirst)}</p>
    <div class="topic-progress">
      <div class="topic-progress-track"><div data-lace="course-progress-bar"></div></div>
      <span class="topic-progress-label"><span data-lace="course-progress">0%</span> through this course</span>
    </div>

    <!-- ── § 1 · The scenario ───────────────────────────────────────────── -->
    <section class="section">
      <div class="section-rule">
        <span class="sr-num">§ 1</span>
        <span class="sr-line"></span>
        <span class="sr-label">The scenario</span>
      </div>
${paragraphs(topic.scenario)}
${mediaFigures(topic, "scenario")}    </section>

    <!-- ── § 2 · The rule ───────────────────────────────────────────────── -->
    <section class="section">
      <div class="section-rule">
        <span class="sr-num">§ 2</span>
        <span class="sr-line"></span>
        <span class="sr-label">The rule</span>
      </div>
${paragraphs(topic.rule)}
${ruleBox(topic)}${mediaFigures(topic, "rule")}    </section>

${whatChangedSection(topic)}${tryItSection(topic).replace("§ 4", `§ ${tryItNum}`)}

    <!-- ── § ${rememberNum} · Remember ───────────────────────────────────────────── -->
    <section class="section">
      <div class="section-rule">
        <span class="sr-num">§ ${rememberNum}</span>
        <span class="sr-line"></span>
        <span class="sr-label">If you remember nothing else</span>
      </div>
      <div class="remember-box">
        <ul>
${topic.remember
  .filter((r) => r.trim())
  .map((r) => `          <li>${inline(r)}</li>`)
  .join("\n")}
        </ul>
      </div>
    </section>

${nextUpSection(draft, flatIndex, flat)}

  </main>
</div>

</body>
</html>
`;
}

/* ── full package ────────────────────────────────────────────────────────── */

export function validateDraft(draft: CourseDraft): string[] {
  const problems: string[] = [];
  if (!draft.courseTitle.trim()) problems.push("Course title is required.");
  if (!draft.courseId.trim()) problems.push("Course id is required.");
  const flat = draft.modules.flatMap((m) => m.topics);
  if (flat.length === 0) problems.push("Add at least one topic.");
  const slugs = new Set<string>();
  for (const topic of flat) {
    if (!topic.slug.trim() || !/^[a-z0-9-]+$/.test(topic.slug)) {
      problems.push(`Topic "${topic.title || topic.slug}" needs a slug (lowercase, hyphens).`);
    }
    if (slugs.has(topic.slug)) problems.push(`Duplicate topic slug: "${topic.slug}".`);
    slugs.add(topic.slug);
    if (!topic.title.trim()) problems.push(`Topic "${topic.slug}" needs a title.`);
    if (topic.tryIt.options.filter((o) => o.text.trim()).length >= 2) {
      if (!topic.tryIt.options.some((o) => o.correct && o.text.trim())) {
        problems.push(`Topic "${topic.title}": mark one Try-it option correct.`);
      }
    }
  }
  return problems;
}

export function referencedImages(draft: CourseDraft): string[] {
  return [
    ...new Set(
      draft.modules
        .flatMap((m) => m.topics)
        .flatMap((t) => t.media ?? [])
        .map((m) => m.filename.trim())
        .filter(Boolean),
    ),
  ];
}

export async function buildPackageFiles(draft: CourseDraft): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  files.set("course-config.js", generateConfigJs(draft));
  for (const topic of draft.modules.flatMap((m) => m.topics)) {
    files.set(`${topic.slug}.html`, generateTopicHtml(draft, topic.slug));
  }
  for (const name of WRAPPER_FILES) {
    files.set(name, await readWrapperFile(name));
  }

  const images = referencedImages(draft);
  if (images.length > 0) {
    files.set(
      "images/README.txt",
      "This course references the following images.\n" +
        "Drop each file into this folder before uploading to Brightspace:\n\n" +
        images.map((name) => `  - ${name}`).join("\n") +
        "\n",
    );
  }
  return files;
}
